# version: "" # TODO: versione docker (?)
name: shokora

services:
  # frontend:
  #   image: nginx
  #   build: frontend/build

  backend:
    image: golang:1.25.4-alpine
    # ports:
    #   - 8080:8080
    depends_on:
      db:
        condition: service_healthy # backend working when db working # TODO: va bene o conviene fare in altro modo (?)
    restart: unless-stopped # TODO: da mettere anche in altri senvizi

  db:
    container_name: postgres-db
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"] # command to execute to test service -> if it exits with 0 is ok
      interval: 10s #1m30s
      timeout: 5s #30s
      retries: 5
      # start_period: 30s # TODO: da usare?
    restart: unless-stopped

volumes:
  pgdata:
# TODO: guarda impostazioni da https://github.com/Melkeydev/yappr (yt: https://www.youtube.com/watch?v=65-y9FaN--s)

# TODO: chiedi conferma su qualche comunità/gruppo riguardo alla struttura del progetto ed alla configurazione docker
