name: shokora-test

services:
  db:
    container_name: postgres-test
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    ports:
      - "5432:5432" #! ATTENZIONE alla porta (potrebbe non funzionare se mappata su una porta esterna a cui accede già postgres locale, ma all'interno dei container non dovrebbero esserci problemi)

volumes:
  pgdata_test:
